name: "release"

# yamllint disable-line rule:truthy 
on:
  push

jobs:
  release:
    name: edit
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: inspect builder
        run: |
          git config --global user.email "jackhunt43@libero.it"
          git config --global user.name "dragonhunt02"
          #chmod +x plugins/traefik-vhosts/subcommands/label
          chmod +x plugins/proxy/command-functions
          git add -A
          git commit -a -m "chmod"
          git push
