name: "release"

# yamllint disable-line rule:truthy
on:
  push

jobs:
  release:
    name: release
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: inspect builder
        run: |
          chmod +x plugins/traefik-vhosts/subcommands/label
          chmod +x plugins/proxy/functions
          git add -A
          git commit -a -m "chmod"
