---
name: "release"

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Release type"
        default: "patch"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
          - build
          - betafish
jobs:
  release:
    name: release
    runs-on: ubuntu-24.04
    env:
      PACKAGECLOUD_TOKEN: ""
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: set up qemu
        uses: docker/setup-qemu-action@v3

      - name: set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

     # - name: install package_cloud
    #    run: gem install package_cloud

     # - name: configure git
      #  run: |
     #     git config --global user.name 'Dokku Bot'
     #     git config --global user.email no-reply@dokku.com

      - name: build package
        env:
          RELEASE_GITHUB_USERNAME: "usertest"
          RELEASE_GITHUB_API_TOKEN: ""
        run: contrib/release-dokku ${{ github.event.inputs.release_type }}


      - name: output version
        id: version
        run: |
          sudo apt install -y tree
          echo "version=$(cat build/next-version)" >> $GITHUB_OUTPUT
          tree -a .
          ls -a -l -R .
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: dokku-${{ github.run_number }}
          release_name: Latest Dokku image tarball
          draft: false
          prerelease: true
          
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dokku-image.tar
          asset_name: dokku-image.tar
          asset_content_type: application/x-tar
          

      #- name: upload packages
      #  uses: actions/upload-artifact@v4
      #  with:
     #     name: build
      #    path: build

